name: Self-hosted Runner Test

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, Linux, X64]
    timeout-minutes: 10

    steps:
      - name: Show runner context
        run: |
          echo "RUNNER_NAME=$RUNNER_NAME"
          echo "RUNNER_OS=$RUNNER_OS"
          echo "RUNNER_ARCH=$RUNNER_ARCH"
          echo "GITHUB_APP_ID=$GITHUB_APP_ID"
          echo "GITHUB_APP_INSTALLATION_ID=$GITHUB_APP_INSTALLATION_ID"
          echo "GITHUB_APP_PRIVATE_KEY_FILE=$GITHUB_APP_PRIVATE_KEY_FILE"
          echo "GITHUB_REPOSIOTRY=$GITHUB_REPOSIOTRY"
